---
apiVersion: v1
kind: Namespace
metadata:
  name: volsync-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    openshift.io/sa.scc.mcs: s0:c26,c20
    openshift.io/sa.scc.supplemental-groups: 1002000000/10000
    openshift.io/sa.scc.uid-range: 1002000000/10000
    volsync.backube/privileged-movers: "true"
