---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cloudflared
  namespace: flux-system
spec:
  targetNamespace: network
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: onepassword-store
  path: ./openshift/apps/network/cloudflared/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: ocp-neptune
  wait: true
  interval: 30m
  timeout: 5m
