---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: webhook-receiver
spec:
  host: flux-webhook.${SECRET_DOMAIN}
  path: /hook/
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: webhook-receiver
    weight: 100
  port:
    targetPort: http
