apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:E0VmH1PMl7T7nTrlsFo=,iv:ecU/ycxnHKDu5R7vhlONfCnTZjDVSnkH9R9Dx9/fvNw=,tag:tPmBIS4qF7s0znwuqyYLug==,type:str]
  SECRET_DOMAIN: ENC[AES256_GCM,data:9BRnngz6vLH6bEr5,iv:5CgsuSV8oumI8/RTKxr8/NvrE6q3YjEog+KjQrg7LzQ=,tag:fjCh/Q54kiVOx3z87qGyag==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gej97akpv0km33qd9s8jurctewcpp046erwwfj44svyzusdxtp9sz506hc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSUJWdnlpLzh2Mlc3MjFJ
        M0E4bG9OZFhGMEdWUTM2cjNMWnFxY1Rxd1VVCkRPblREdEFEcERnMkJwTGtXVGxE
        L3daUDNkUzhnYU9rdndmNi9JNnlKUmcKLS0tIExldFZIYzdGWko3RFdHUlYzdGQv
        Z0IrS2VjdlNkVjRwZGM3dGIzQ1J1UncKPC6jCRyuhmHnqemLn+HaZ1eGtVLnG4R4
        ONcKXvP8BYqbArQdF6pcfkO0vvOEE8K1m5S9guP9kKj7FemFpmdVqA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-20T03:35:29Z"
  mac: ENC[AES256_GCM,data:FVOjpaBvMeD7CXmGKVlaqaM60tdJDB7EuF9nZ4pUeigzdcXDN2fK16IWQor0Ucy6J5qZAfJLNlYZijTqjr/M/w8mQspvKXv+MUBMYMstnYNy3p0tcs6JKdgDEc8kMJCZY6Ik6OCeWt52OEiPVWgtBW7iotvyaMQOCCuA+oyzn68=,iv:rKAqvSPO2ZRtMSrWDu7KPTKFX9ioXSaUAwjErgKQ0vU=,tag:n1/UDIivAur3NB+uJ7D/Yw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.2
