apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:62BsmaxAGQylRrV9D90yPIRXLrGr6jlV2egQkcNXOXQ=,iv:G+ViDi0HwypkEcWQ7/7atEx4+Ln9tvEDnwIajC1/OJE=,tag:cxzUBCWU8YII0gcdQL8pzA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:E0VmH1PMl7T7nTrlsFo=,iv:ecU/ycxnHKDu5R7vhlONfCnTZjDVSnkH9R9Dx9/fvNw=,tag:tPmBIS4qF7s0znwuqyYLug==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_SECRET: ENC[AES256_GCM,data:Y4JWKzcmoJeJqy+GbHZYqVPzWl+YHy4g/+B8mMHRIa8t5RoYTiXY2ywlFTw95CR0nKGBq5bRSkFyLBPDcDIhWHwz0yUDc2jEmX6S3jZEE1qpHND/5Nl3pvNNFDKiOlVJvbD4kkrn9yY5ZrzdVxHqpHHylMMcmellI944jdqWR5idtj2rWix+UBRMicWkKDs/AL9z88Q6f8+JUVh+xx9Ih9pQWrQWkrBtdnkSDpd1PYuRt48KfI8GOA==,iv:hXe3SMj02n9bp5zNBVvDJAmfHVjoBH8UwMdwv0Xg3Pw=,tag:2q/eRjr011iDbkbsu7h0Zw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:9BRnngz6vLH6bEr5,iv:5CgsuSV8oumI8/RTKxr8/NvrE6q3YjEog+KjQrg7LzQ=,tag:fjCh/Q54kiVOx3z87qGyag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gej97akpv0km33qd9s8jurctewcpp046erwwfj44svyzusdxtp9sz506hc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSUJWdnlpLzh2Mlc3MjFJ
            M0E4bG9OZFhGMEdWUTM2cjNMWnFxY1Rxd1VVCkRPblREdEFEcERnMkJwTGtXVGxE
            L3daUDNkUzhnYU9rdndmNi9JNnlKUmcKLS0tIExldFZIYzdGWko3RFdHUlYzdGQv
            Z0IrS2VjdlNkVjRwZGM3dGIzQ1J1UncKPC6jCRyuhmHnqemLn+HaZ1eGtVLnG4R4
            ONcKXvP8BYqbArQdF6pcfkO0vvOEE8K1m5S9guP9kKj7FemFpmdVqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-22T03:59:37Z"
    mac: ENC[AES256_GCM,data:eUjid6pzTJweTYPN9bliz5sMLlrWLnbjGD0ZyPQrTT4R6TQfVDlvF6opbNMG4/42Cp0zyfzkGiYotIbqbiV1S7yeWCYGG36PRFqPE4M1RkoRtvdnklIHwHqoJOchSY+X3ZUW8Bdw6nNLpj1aT3Krqy6/A1urqihrLR/0NmmCdaU=,iv:YWBkT8J/GcQcXXAnP128UYRuy8Hl2yXsVayZnBJaIYE=,tag:W9r2TKcVhHkmY5hcEpFTqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.2
